'use strict';

// /**
//  * AngularJS default filter with the following expression:
//  * "person in people | filter: {name: $select.search, age: $select.search}"
//  * performs a AND between 'name: $select.search' and 'age: $select.search'.
//  * We want to perform a OR.
//  */
// quotesApp.filter('propsFilter', function() {
//   return function(items, props) {
//     var out = [];

//     if (angular.isArray(items)) {
//       items.forEach(function(item) {
//         var itemMatches = false;

//         var keys = Object.keys(props);
//         for (var i = 0; i < keys.length; i++) {
//           var prop = keys[i];
//           var text = props[prop].toLowerCase();
//           if (item[prop].toString().toLowerCase().indexOf(text) !== -1) {
//             itemMatches = true;
//             break;
//           }
//         }

//         if (itemMatches) {
//           out.push(item);
//         }
//       });
//     } else {
//       // Let the output be the input untouched
//       out = items;
//     }

//     return out;
//   }
// });

quotesApp.controller('DemoCtrl', function($scope, $http) {
  // $scope.disabled = undefined;

  // $scope.enable = function() {
  //   $scope.disabled = false;
  // };

  // $scope.disable = function() {
  //   $scope.disabled = true;
  // };

  // $scope.clear = function() {
  //   $scope.person.selected = undefined;
  //   $scope.address.selected = undefined;
  //   $scope.country.selected = undefined;
  // };

  // $scope.person = {};
  // $scope.people = [
  //   { name: 'Adam',      email: 'adam@email.com',      age: 10 },
  //   { name: 'Amalie',    email: 'amalie@email.com',    age: 12 },
  //   { name: 'Wladimir',  email: 'wladimir@email.com',  age: 30 },
  //   { name: 'Samantha',  email: 'samantha@email.com',  age: 31 },
  //   { name: 'Estefanía', email: 'estefanía@email.com', age: 16 },
  //   { name: 'Natasha',   email: 'natasha@email.com',   age: 54 },
  //   { name: 'Nicole',    email: 'nicole@email.com',    age: 43 },
  //   { name: 'Adrian',    email: 'adrian@email.com',    age: 21 }
  // ];

  // $scope.address = {};
  // $scope.refreshAddresses = function(address) {
  //   var params = {address: address, sensor: false};
  //   return $http.get(
  //     'http://maps.googleapis.com/maps/api/geocode/json',
  //     {params: params}
  //   ).then(function(response) {
  //     $scope.addresses = response.data.results
  //   });
  // };

  $scope.quote = {};
  $scope.quotes = [ 
  {ticker: 'MMM', Name: '3M Company', Sector: 'Industrials'},
  {ticker: 'ABT', Name: 'Abbott Laboratories', Sector: 'Health Care'},
  {ticker: 'ABBV', Name: 'AbbVie', Sector: 'Health Care'},
  {ticker: 'ACN', Name: 'Accenture plc', Sector: 'Information Technology'},
  {ticker: 'ATVI', Name: 'Activision Blizzard', Sector: 'Information Technology'},
  {ticker: 'AYI', Name: 'Acuity Brands Inc', Sector: 'Industrials'},
  {ticker: 'ADBE', Name: 'Adobe Systems Inc', Sector: 'Information Technology'},
  {ticker: 'AAP', Name: 'Advance Auto Parts', Sector: 'Consumer Discretionary'},
  {ticker: 'AES', Name: 'AES Corp', Sector: 'Utilities'},
  {ticker: 'AET', Name: 'Aetna Inc', Sector: 'Health Care'},
  {ticker: 'AMG', Name: 'Affiliated Managers Group Inc', Sector: 'Financials'},
  {ticker: 'AFL', Name: 'AFLAC Inc', Sector: 'Financials'},
  {ticker: 'A', Name: 'Agilent Technologies Inc', Sector: 'Health Care'},
  {ticker: 'APD', Name: 'Air Products & Chemicals Inc', Sector: 'Materials'},
  {ticker: 'AKAM', Name: 'Akamai Technologies Inc', Sector: 'Information Technology'},
  {ticker: 'ALK', Name: 'Alaska Air Group Inc', Sector: 'Industrials'},
  {ticker: 'ALB', Name: 'Albemarle Corp', Sector: 'Materials'},
  {ticker: 'AA', Name: 'Alcoa Inc', Sector: 'Materials'},
  {ticker: 'ALXN', Name: 'Alexion Pharmaceuticals', Sector: 'Health Care'},
  {ticker: 'ALLE', Name: 'Allegion', Sector: 'Industrials'},
  {ticker: 'AGN', Name: 'Allergan plc', Sector: 'Health Care'},
  {ticker: 'ADS', Name: 'Alliance Data Systems', Sector: 'Information Technology'},
  {ticker: 'LNT', Name: 'Alliant Energy Corp', Sector: 'Utilities'},
  {ticker: 'ALL', Name: 'Allstate Corp', Sector: 'Financials'},
  {ticker: 'GOOGL', Name: 'Alphabet Inc Class A', Sector: 'Information Technology'},
  {ticker: 'GOOG', Name: 'Alphabet Inc Class C', Sector: 'Information Technology'},
  {ticker: 'MO', Name: 'Altria Group Inc', Sector: 'Consumer Staples'},
  {ticker: 'AMZN', Name: 'Amazon.com Inc', Sector: 'Consumer Discretionary'},
  {ticker: 'AEE', Name: 'Ameren Corp', Sector: 'Utilities'},
  {ticker: 'AAL', Name: 'American Airlines Group', Sector: 'Industrials'},
  {ticker: 'AEP', Name: 'American Electric Power', Sector: 'Utilities'},
  {ticker: 'AXP', Name: 'American Express Co', Sector: 'Financials'},
  {ticker: 'AIG', Name: 'American International Group, Inc.', Sector: 'Financials'},
  {ticker: 'AMT', Name: 'American Tower Corp A', Sector: 'Financials'},
  {ticker: 'AWK', Name: 'American Water Works Company Inc', Sector: 'Utilities'},
  {ticker: 'AMP', Name: 'Ameriprise Financial', Sector: 'Financials'},
  {ticker: 'ABC', Name: 'AmerisourceBergen Corp', Sector: 'Health Care'},
  {ticker: 'AME', Name: 'Ametek', Sector: 'Industrials'},
  {ticker: 'AMGN', Name: 'Amgen Inc', Sector: 'Health Care'},
  {ticker: 'APH', Name: 'Amphenol Corp A', Sector: 'Industrials'},
  {ticker: 'APC', Name: 'Anadarko Petroleum Corp', Sector: 'Energy'},
  {ticker: 'ADI', Name: 'Analog Devices, Inc.', Sector: 'Information Technology'},
  {ticker: 'ANTM', Name: 'Anthem Inc.', Sector: 'Health Care'},
  {ticker: 'AON', Name: 'Aon plc', Sector: 'Financials'},
  {ticker: 'APA', Name: 'Apache Corporation', Sector: 'Energy'},
  {ticker: 'AIV', Name: 'Apartment Investment & Mgmt', Sector: 'Financials'},
  {ticker: 'AAPL', Name: 'Apple Inc.', Sector: 'Information Technology'},
  {ticker: 'AMAT', Name: 'Applied Materials Inc', Sector: 'Information Technology'},
  {ticker: 'ADM', Name: 'Archer-Daniels-Midland Co', Sector: 'Consumer Staples'},
  {ticker: 'AJG', Name: 'Arthur J. Gallagher & Co.', Sector: 'Financials'},
  {ticker: 'AIZ', Name: 'Assurant Inc', Sector: 'Financials'},
  {ticker: 'T', Name: 'AT&T Inc', Sector: 'Telecommunications Services'},
  {ticker: 'ADSK', Name: 'Autodesk Inc', Sector: 'Information Technology'},
  {ticker: 'ADP', Name: 'Automatic Data Processing', Sector: 'Information Technology'},
  {ticker: 'AN', Name: 'AutoNation Inc', Sector: 'Consumer Discretionary'},
  {ticker: 'AZO', Name: 'AutoZone Inc', Sector: 'Consumer Discretionary'},
  {ticker: 'AVGO', Name: 'Avago Technologies', Sector: 'Information Technology'},
  {ticker: 'AVB', Name: 'AvalonBay Communities, Inc.', Sector: 'Financials'},
  {ticker: 'AVY', Name: 'Avery Dennison Corp', Sector: 'Materials'},
  {ticker: 'BHI', Name: 'Baker Hughes Inc', Sector: 'Energy'},
  {ticker: 'BLL', Name: 'Ball Corp', Sector: 'Materials'},
  {ticker: 'BAC', Name: 'Bank of America Corp', Sector: 'Financials'},
  {ticker: 'BCR', Name: 'Bard (C.R.) Inc.', Sector: 'Health Care'},
  {ticker: 'BAX', Name: 'Baxter International Inc.', Sector: 'Health Care'},
  {ticker: 'BBT', Name: 'BB&T Corporation', Sector: 'Financials'},
  {ticker: 'BDX', Name: 'Becton Dickinson', Sector: 'Health Care'},
  {ticker: 'BBBY', Name: 'Bed Bath & Beyond', Sector: 'Consumer Discretionary'},
  {ticker: 'BRK-B', Name: 'Berkshire Hathaway', Sector: 'Financials'},
  {ticker: 'BBY', Name: 'Best Buy Co. Inc.', Sector: 'Consumer Discretionary'},
  {ticker: 'BIIB', Name: 'BIOGEN IDEC Inc.', Sector: 'Health Care'},
  {ticker: 'BLK', Name: 'BlackRock', Sector: 'Financials'},
  {ticker: 'HRB', Name: 'Block H&R', Sector: 'Financials'},
  {ticker: 'BA', Name: 'Boeing Company', Sector: 'Industrials'},
  {ticker: 'BWA', Name: 'BorgWarner', Sector: 'Consumer Discretionary'},
  {ticker: 'BXP', Name: 'Boston Properties', Sector: 'Financials'},
  {ticker: 'BSX', Name: 'Boston Scientific', Sector: 'Health Care'},
  {ticker: 'BMY', Name: 'Bristol-Myers Squibb', Sector: 'Health Care'},
  {ticker: 'BF-B', Name: 'Brown-Forman Corporation', Sector: 'Consumer Staples'},
  {ticker: 'CHRW', Name: 'C. H. Robinson Worldwide', Sector: 'Industrials'},
  {ticker: 'CA', Name: 'CA, Inc.', Sector: 'Information Technology'},
  {ticker: 'COG', Name: 'Cabot Oil & Gas', Sector: 'Energy'},
  {ticker: 'CPB', Name: 'Campbell Soup', Sector: 'Consumer Staples'},
  {ticker: 'COF', Name: 'Capital One Financial', Sector: 'Financials'},
  {ticker: 'CAH', Name: 'Cardinal Health Inc.', Sector: 'Health Care'},
  {ticker: 'KMX', Name: 'Carmax Inc', Sector: 'Consumer Discretionary'},
  {ticker: 'CCL', Name: 'Carnival Corp.', Sector: 'Consumer Discretionary'},
  {ticker: 'CAT', Name: 'Caterpillar Inc.', Sector: 'Industrials'},
  {ticker: 'CBG', Name: 'CBRE Group', Sector: 'Financials'},
  {ticker: 'CBS', Name: 'CBS Corp.', Sector: 'Consumer Discretionary'},
  {ticker: 'CELG', Name: 'Celgene Corp.', Sector: 'Health Care'},
  {ticker: 'CNC', Name: 'Centene Corporation', Sector: 'Health Care'},
  {ticker: 'CNP', Name: 'CenterPoint Energy', Sector: 'Utilities'},
  {ticker: 'CTL', Name: 'CenturyLink Inc', Sector: 'Telecommunications Services'},
  {ticker: 'CERN', Name: 'Cerner', Sector: 'Health Care'},
  {ticker: 'CF', Name: 'CF Industries Holdings Inc', Sector: 'Materials'},
  {ticker: 'SCHW', Name: 'Charles Schwab Corporation', Sector: 'Financials'},
  {ticker: 'CHK', Name: 'Chesapeake Energy', Sector: 'Energy'},
  {ticker: 'CVX', Name: 'Chevron Corp.', Sector: 'Energy'},
  {ticker: 'CMG', Name: 'Chipotle Mexican Grill', Sector: 'Consumer Discretionary'},
  {ticker: 'CB', Name: 'Chubb Limited', Sector: 'Financials'},
  {ticker: 'CHD', Name: 'Church & Dwight', Sector: 'Consumer Staples'},
  {ticker: 'CI', Name: 'CIGNA Corp.', Sector: 'Health Care'},
  {ticker: 'XEC', Name: 'Cimarex Energy', Sector: 'Energy'},
  {ticker: 'CINF', Name: 'Cincinnati Financial', Sector: 'Financials'},
  {ticker: 'CTAS', Name: 'Cintas Corporation', Sector: 'Industrials'},
  {ticker: 'CSCO', Name: 'Cisco Systems', Sector: 'Information Technology'},
  {ticker: 'C', Name: 'Citigroup Inc.', Sector: 'Financials'},
  {ticker: 'CFG', Name: 'Citizens Financial Group', Sector: 'Financials'},
  {ticker: 'CTXS', Name: 'Citrix Systems', Sector: 'Information Technology'},
  {ticker: 'CME', Name: 'CME Group Inc.', Sector: 'Financials'},
  {ticker: 'CMS', Name: 'CMS Energy', Sector: 'Utilities'},
  {ticker: 'COH', Name: 'Coach Inc.', Sector: 'Consumer Discretionary'},
  {ticker: 'CTSH', Name: 'Cognizant Technology Solutions', Sector: 'Information Technology'},
  {ticker: 'CL', Name: 'Colgate-Palmolive', Sector: 'Consumer Staples'},
  {ticker: 'CMCSA', Name: 'Comcast A Corp', Sector: 'Consumer Discretionary'},
  {ticker: 'CMA', Name: 'Comerica Inc.', Sector: 'Financials'},
  {ticker: 'CAG', Name: 'ConAgra Foods Inc.', Sector: 'Consumer Staples'},
  {ticker: 'CXO', Name: 'Concho Resources', Sector: 'Energy'},
  {ticker: 'COP', Name: 'ConocoPhillips', Sector: 'Energy'},
  {ticker: 'ED', Name: 'Consolidated Edison', Sector: 'Utilities'},
  {ticker: 'STZ', Name: 'Constellation Brands', Sector: 'Consumer Staples'},
  {ticker: 'GLW', Name: 'Corning Inc.', Sector: 'Industrials'},
  {ticker: 'COST', Name: 'Costco Co.', Sector: 'Consumer Staples'},
  {ticker: 'CCI', Name: 'Crown Castle International Corp.', Sector: 'Financials'},
  {ticker: 'CSRA', Name: 'CSRA Inc.', Sector: 'Information Technology'},
  {ticker: 'CSX', Name: 'CSX Corp.', Sector: 'Industrials'},
  {ticker: 'CMI', Name: 'Cummins Inc.', Sector: 'Industrials'},
  {ticker: 'CVS', Name: 'CVS Health', Sector: 'Consumer Staples'},
  {ticker: 'DHI', Name: 'D. R. Horton', Sector: 'Consumer Discretionary'},
  {ticker: 'DHR', Name: 'Danaher Corp.', Sector: 'Industrials'},
  {ticker: 'DRI', Name: 'Darden Restaurants', Sector: 'Consumer Discretionary'},
  {ticker: 'DVA', Name: 'DaVita Inc.', Sector: 'Health Care'},
  {ticker: 'DE', Name: 'Deere & Co.', Sector: 'Industrials'},
  {ticker: 'DLPH', Name: 'Delphi Automotive', Sector: 'Consumer Discretionary'},
  {ticker: 'DAL', Name: 'Delta Air Lines', Sector: 'Industrials'},
  {ticker: 'XRAY', Name: 'Dentsply Sirona', Sector: 'Health Care'},
  {ticker: 'DVN', Name: 'Devon Energy Corp.', Sector: 'Energy'},
  {ticker: 'DO', Name: 'Diamond Offshore Drilling', Sector: 'Energy'},
  {ticker: 'DLR', Name: 'Digital Realty Trust', Sector: 'Financials'},
  {ticker: 'DFS', Name: 'Discover Financial Services', Sector: 'Financials'},
  {ticker: 'DISCA', Name: 'Discovery Communications-A', Sector: 'Consumer Discretionary'},
  {ticker: 'DISCK', Name: 'Discovery Communications-C', Sector: 'Consumer Discretionary'},
  {ticker: 'DG', Name: 'Dollar General', Sector: 'Consumer Discretionary'},
  {ticker: 'DLTR', Name: 'Dollar Tree', Sector: 'Consumer Discretionary'},
  {ticker: 'D', Name: 'Dominion Resources', Sector: 'Utilities'},
  {ticker: 'DOV', Name: 'Dover Corp.', Sector: 'Industrials'},
  {ticker: 'DOW', Name: 'Dow Chemical', Sector: 'Materials'},
  {ticker: 'DPS', Name: 'Dr Pepper Snapple Group', Sector: 'Consumer Staples'},
  {ticker: 'DTE', Name: 'DTE Energy Co.', Sector: 'Utilities'},
  {ticker: 'DD', Name: 'Du Pont (E.I.)', Sector: 'Materials'},
  {ticker: 'DUK', Name: 'Duke Energy', Sector: 'Utilities'},
  {ticker: 'DNB', Name: 'Dun & Bradstreet', Sector: 'Industrials'},
  {ticker: 'ETFC', Name: 'E*Trade', Sector: 'Financials'},
  {ticker: 'EMN', Name: 'Eastman Chemical', Sector: 'Materials'},
  {ticker: 'ETN', Name: 'Eaton Corporation', Sector: 'Industrials'},
  {ticker: 'EBAY', Name: 'eBay Inc.', Sector: 'Information Technology'},
  {ticker: 'ECL', Name: 'Ecolab Inc.', Sector: 'Materials'},
  {ticker: 'EIX', Name: 'Edison Intl', Sector: 'Utilities'},
  {ticker: 'EW', Name: 'Edwards Lifesciences', Sector: 'Health Care'},
  {ticker: 'EA', Name: 'Electronic Arts', Sector: 'Information Technology'},
  {ticker: 'EMC', Name: 'EMC Corp.', Sector: 'Information Technology'},
  {ticker: 'EMR', Name: 'Emerson Electric Company', Sector: 'Industrials'},
  {ticker: 'ENDP', Name: 'Endo International', Sector: 'Health Care'},
  {ticker: 'ETR', Name: 'Entergy Corp.', Sector: 'Utilities'},
  {ticker: 'EOG', Name: 'EOG Resources', Sector: 'Energy'},
  {ticker: 'EQT', Name: 'EQT Corporation', Sector: 'Energy'},
  {ticker: 'EFX', Name: 'Equifax Inc.', Sector: 'Financials'},
  {ticker: 'EQIX', Name: 'Equinix', Sector: 'Information Technology'},
  {ticker: 'EQR', Name: 'Equity Residential', Sector: 'Financials'},
  {ticker: 'ESS', Name: 'Essex Property Trust Inc', Sector: 'Financials'},
  {ticker: 'EL', Name: 'Estee Lauder Cos.', Sector: 'Consumer Staples'},
  {ticker: 'ES', Name: 'Eversource Energy', Sector: 'Utilities'},
  {ticker: 'EXC', Name: 'Exelon Corp.', Sector: 'Utilities'},
  {ticker: 'EXPE', Name: 'Expedia Inc.', Sector: 'Consumer Discretionary'},
  {ticker: 'EXPD', Name: 'Expeditors Intl', Sector: 'Industrials'},
  {ticker: 'ESRX', Name: 'Express Scripts', Sector: 'Health Care'},
  {ticker: 'EXR', Name: 'Extra Space Storage', Sector: 'Financials'},
  {ticker: 'XOM', Name: 'Exxon Mobil Corp.', Sector: 'Energy'},
  {ticker: 'FFIV', Name: 'F5 Networks', Sector: 'Information Technology'},
  {ticker: 'FB', Name: 'Facebook', Sector: 'Information Technology'},
  {ticker: 'FAST', Name: 'Fastenal Co', Sector: 'Industrials'},
  {ticker: 'FRT', Name: 'Federal Realty Investment Trust', Sector: 'Financials'},
  {ticker: 'FDX', Name: 'FedEx Corporation', Sector: 'Industrials'},
  {ticker: 'FIS', Name: 'Fidelity National Information Services', Sector: 'Information Technology'},
  {ticker: 'FITB', Name: 'Fifth Third Bancorp', Sector: 'Financials'},
  {ticker: 'FSLR', Name: 'First Solar Inc', Sector: 'Information Technology'},
  {ticker: 'FE', Name: 'FirstEnergy Corp', Sector: 'Utilities'},
  {ticker: 'FISV', Name: 'Fiserv Inc', Sector: 'Information Technology'},
  {ticker: 'FLIR', Name: 'FLIR Systems', Sector: 'Industrials'},
  {ticker: 'FLS', Name: 'Flowserve Corporation', Sector: 'Industrials'},
  {ticker: 'FLR', Name: 'Fluor Corp.', Sector: 'Industrials'},
  {ticker: 'FMC', Name: 'FMC Corporation', Sector: 'Materials'},
  {ticker: 'FTI', Name: 'FMC Technologies Inc.', Sector: 'Energy'},
  {ticker: 'FL', Name: 'Foot Locker Inc', Sector: 'Consumer Discretionary'},
  {ticker: 'F', Name: 'Ford Motor', Sector: 'Consumer Discretionary'},
  {ticker: 'FTV', Name: 'Fortive Corp', Sector: 'Industrials'},
  {ticker: 'FBHS', Name: 'Fortune Brands Home & Security', Sector: 'Industrials'},
  {ticker: 'BEN', Name: 'Franklin Resources', Sector: 'Financials'},
  {ticker: 'FCX', Name: 'Freeport-McMoran Cp & Gld', Sector: 'Materials'},
  {ticker: 'FTR', Name: 'Frontier Communications', Sector: 'Telecommunications Services'},
  {ticker: 'GPS', Name: 'Gap (The)', Sector: 'Consumer Discretionary'},
  {ticker: 'GRMN', Name: 'Garmin Ltd.', Sector: 'Consumer Discretionary'},
  {ticker: 'GD', Name: 'General Dynamics', Sector: 'Industrials'},
  {ticker: 'GE', Name: 'General Electric', Sector: 'Industrials'},
  {ticker: 'GGP', Name: 'General Growth Properties Inc.', Sector: 'Financials'},
  {ticker: 'GIS', Name: 'General Mills', Sector: 'Consumer Staples'},
  {ticker: 'GM', Name: 'General Motors', Sector: 'Consumer Discretionary'},
  {ticker: 'GPC', Name: 'Genuine Parts', Sector: 'Consumer Discretionary'},
  {ticker: 'GILD', Name: 'Gilead Sciences', Sector: 'Health Care'},
  {ticker: 'GPN', Name: 'Global Payments Inc', Sector: 'Information Technology'},
  {ticker: 'GS', Name: 'Goldman Sachs Group', Sector: 'Financials'},
  {ticker: 'GT', Name: 'Goodyear Tire & Rubber', Sector: 'Consumer Discretionary'},
  {ticker: 'GWW', Name: 'Grainger (W.W.) Inc.', Sector: 'Industrials'},
  {ticker: 'HAL', Name: 'Halliburton Co.', Sector: 'Energy'},
  {ticker: 'HBI', Name: 'Hanesbrands Inc', Sector: 'Consumer Discretionary'},
  {ticker: 'HOG', Name: 'Harley-Davidson', Sector: 'Consumer Discretionary'},
  {ticker: 'HAR', Name: 'Harman Intl Industries', Sector: 'Consumer Discretionary'},
  {ticker: 'HRS', Name: 'Harris Corporation', Sector: 'Information Technology'},
  {ticker: 'HIG', Name: 'Hartford Financial Svc.Gp.', Sector: 'Financials'},
  {ticker: 'HAS', Name: 'Hasbro Inc.', Sector: 'Consumer Discretionary'},
  {ticker: 'HCA', Name: 'HCA Holdings', Sector: 'Health Care'},
  {ticker: 'HCP', Name: 'HCP Inc.', Sector: 'Financials'},
  {ticker: 'HP', Name: 'Helmerich & Payne', Sector: 'Energy'},
  {ticker: 'HSIC', Name: 'Henry Schein', Sector: 'Health Care'},
  {ticker: 'HES', Name: 'Hess Corporation', Sector: 'Energy'},
  {ticker: 'HPE', Name: 'Hewlett Packard Enterprise', Sector: 'Information Technology'},
  {ticker: 'HOLX', Name: 'Hologic', Sector: 'Health Care'},
  {ticker: 'HD', Name: 'Home Depot', Sector: 'Consumer Discretionary'},
  {ticker: 'HON', Name: 'Honeywell Intl Inc.', Sector: 'Industrials'},
  {ticker: 'HRL', Name: 'Hormel Foods Corp.', Sector: 'Consumer Staples'},
  {ticker: 'HST', Name: 'Host Hotels & Resorts', Sector: 'Financials'},
  {ticker: 'HPQ', Name: 'HP Inc.', Sector: 'Information Technology'},
  {ticker: 'HUM', Name: 'Humana Inc.', Sector: 'Health Care'},
  {ticker: 'HBAN', Name: 'Huntington Bancshares', Sector: 'Financials'},
  {ticker: 'ITW', Name: 'Illinois Tool Works', Sector: 'Industrials'},
  {ticker: 'ILMN', Name: 'Illumina Inc', Sector: 'Health Care'},
  {ticker: 'IR', Name: 'Ingersoll-Rand PLC', Sector: 'Industrials'},
  {ticker: 'INTC', Name: 'Intel Corp.', Sector: 'Information Technology'},
  {ticker: 'ICE', Name: 'Intercontinental Exchange', Sector: 'Financials'},
  {ticker: 'IBM', Name: 'International Bus. Machines', Sector: 'Information Technology'},
  {ticker: 'IP', Name: 'International Paper', Sector: 'Materials'},
  {ticker: 'IPG', Name: 'Interpublic Group', Sector: 'Consumer Discretionary'},
  {ticker: 'IFF', Name: 'Intl Flavors & Fragrances', Sector: 'Materials'},
  {ticker: 'INTU', Name: 'Intuit Inc.', Sector: 'Information Technology'},
  {ticker: 'ISRG', Name: 'Intuitive Surgical Inc.', Sector: 'Health Care'},
  {ticker: 'IVZ', Name: 'Invesco Ltd.', Sector: 'Financials'},
  {ticker: 'IRM', Name: 'Iron Mountain Incorporated', Sector: 'Industrials'},
  {ticker: 'JBHT', Name: 'J. B. Hunt Transport Services', Sector: 'Industrials'},
  {ticker: 'JEC', Name: 'Jacobs Engineering Group', Sector: 'Industrials'},
  {ticker: 'JNJ', Name: 'Johnson & Johnson', Sector: 'Health Care'},
  {ticker: 'JCI', Name: 'Johnson Controls', Sector: 'Consumer Discretionary'},
  {ticker: 'JPM', Name: 'JPMorgan Chase & Co.', Sector: 'Financials'},
  {ticker: 'JNPR', Name: 'Juniper Networks', Sector: 'Information Technology'},
  {ticker: 'KSU', Name: 'Kansas City Southern', Sector: 'Industrials'},
  {ticker: 'K', Name: 'Kellogg Co.', Sector: 'Consumer Staples'},
  {ticker: 'KEY', Name: 'KeyCorp', Sector: 'Financials'},
  {ticker: 'KMB', Name: 'Kimberly-Clark', Sector: 'Consumer Staples'},
  {ticker: 'KIM', Name: 'Kimco Realty', Sector: 'Financials'},
  {ticker: 'KMI', Name: 'Kinder Morgan', Sector: 'Energy'},
  {ticker: 'KLAC', Name: 'KLA-Tencor Corp.', Sector: 'Information Technology'},
  {ticker: 'KSS', Name: 'Kohls Corp.', Sector: 'Consumer Discretionary'},
  {ticker: 'KHC', Name: 'Kraft Heinz Co', Sector: 'Consumer Staples'},
  {ticker: 'KR', Name: 'Kroger Co.', Sector: 'Consumer Staples'},
  {ticker: 'LB', Name: 'L Brands Inc.', Sector: 'Consumer Discretionary'},
  {ticker: 'LLL', Name: 'L-3 Communications Holdings', Sector: 'Industrials'},
  {ticker: 'LH', Name: 'Laboratory Corp. of America Holding', Sector: 'Health Care'},
  {ticker: 'LRCX', Name: 'Lam Research', Sector: 'Information Technology'},
  {ticker: 'LM', Name: 'Legg Mason', Sector: 'Financials'},
  {ticker: 'LEG', Name: 'Leggett & Platt', Sector: 'Industrials'},
  {ticker: 'LEN', Name: 'Lennar Corp.', Sector: 'Consumer Discretionary'},
  {ticker: 'LUK', Name: 'Leucadia National Corp.', Sector: 'Financials'},
  {ticker: 'LVLT', Name: 'Level 3 Communications', Sector: 'Telecommunications Services'},
  {ticker: 'LLY', Name: 'Lilly (Eli) & Co.', Sector: 'Health Care'},
  {ticker: 'LNC', Name: 'Lincoln National', Sector: 'Financials'},
  {ticker: 'LLTC', Name: 'Linear Technology Corp.', Sector: 'Information Technology'},
  {ticker: 'LKQ', Name: 'LKQ Corporation', Sector: 'Consumer Discretionary'},
  {ticker: 'LMT', Name: 'Lockheed Martin Corp.', Sector: 'Industrials'},
  {ticker: 'L', Name: 'Loews Corp.', Sector: 'Financials'},
  {ticker: 'LOW', Name: 'Lowes Cos.', Sector: 'Consumer Discretionary'},
  {ticker: 'LYB', Name: 'LyondellBasell', Sector: 'Materials'},
  {ticker: 'MTB', Name: 'M&T Bank Corp.', Sector: 'Financials'},
  {ticker: 'MAC', Name: 'Macerich', Sector: 'Financials'},
  {ticker: 'M', Name: 'Macys Inc.', Sector: 'Consumer Discretionary'},
  {ticker: 'MNK', Name: 'Mallinckrodt Plc', Sector: 'Health Care'},
  {ticker: 'MRO', Name: 'Marathon Oil Corp.', Sector: 'Energy'},
  {ticker: 'MPC', Name: 'Marathon Petroleum', Sector: 'Energy'},
  {ticker: 'MAR', Name: 'Marriott Intl.', Sector: 'Consumer Discretionary'},
  {ticker: 'MMC', Name: 'Marsh & McLennan', Sector: 'Financials'},
  {ticker: 'MLM', Name: 'Martin Marietta Materials', Sector: 'Materials'},
  {ticker: 'MAS', Name: 'Masco Corp.', Sector: 'Industrials'},
  {ticker: 'MA', Name: 'Mastercard Inc.', Sector: 'Information Technology'},
  {ticker: 'MAT', Name: 'Mattel Inc.', Sector: 'Consumer Discretionary'},
  {ticker: 'MKC', Name: 'McCormick & Co.', Sector: 'Consumer Staples'},
  {ticker: 'MCD', Name: 'McDonalds Corp.', Sector: 'Consumer Discretionary'},
  {ticker: 'MCK', Name: 'McKesson Corp.', Sector: 'Health Care'},
  {ticker: 'MJN', Name: 'Mead Johnson', Sector: 'Consumer Staples'},
  {ticker: 'MDT', Name: 'Medtronic plc', Sector: 'Health Care'},
  {ticker: 'MRK', Name: 'Merck & Co.', Sector: 'Health Care'},
  {ticker: 'MET', Name: 'MetLife Inc.', Sector: 'Financials'},
  {ticker: 'KORS', Name: 'Michael Kors Holdings', Sector: 'Consumer Discretionary'},
  {ticker: 'MCHP', Name: 'Microchip Technology', Sector: 'Information Technology'},
  {ticker: 'MU', Name: 'Micron Technology', Sector: 'Information Technology'},
  {ticker: 'MSFT', Name: 'Microsoft Corp.', Sector: 'Information Technology'},
  {ticker: 'MHK', Name: 'Mohawk Industries', Sector: 'Consumer Discretionary'},
  {ticker: 'TAP', Name: 'Molson Coors Brewing Company', Sector: 'Consumer Staples'},
  {ticker: 'MDLZ', Name: 'Mondelez International', Sector: 'Consumer Staples'},
  {ticker: 'MON', Name: 'Monsanto Co.', Sector: 'Materials'},
  {ticker: 'MNST', Name: 'Monster Beverage', Sector: 'Consumer Staples'},
  {ticker: 'MCO', Name: 'Moodys Corp', Sector: 'Financials'},
  {ticker: 'MS', Name: 'Morgan Stanley', Sector: 'Financials'},
  {ticker: 'MSI', Name: 'Motorola Solutions Inc.', Sector: 'Information Technology'},
  {ticker: 'MUR', Name: 'Murphy Oil', Sector: 'Energy'},
  {ticker: 'MYL', Name: 'Mylan N.V.', Sector: 'Health Care'},
  {ticker: 'NDAQ', Name: 'NASDAQ OMX Group', Sector: 'Financials'},
  {ticker: 'NOV', Name: 'National Oilwell Varco Inc.', Sector: 'Energy'},
  {ticker: 'NAVI', Name: 'Navient', Sector: 'Financials'},
  {ticker: 'NTAP', Name: 'NetApp', Sector: 'Information Technology'},
  {ticker: 'NFLX', Name: 'Netflix Inc.', Sector: 'Information Technology'},
  {ticker: 'NWL', Name: 'Newell Rubbermaid Co.', Sector: 'Consumer Discretionary'},
  {ticker: 'NFX', Name: 'Newfield Exploration Co', Sector: 'Energy'},
  {ticker: 'NEM', Name: 'Newmont Mining Corp. (Hldg. Co.)', Sector: 'Materials'},
  {ticker: 'NWSA', Name: 'News Corp. Class A', Sector: 'Consumer Discretionary'},
  {ticker: 'NWS', Name: 'News Corp. Class B', Sector: 'Consumer Discretionary'},
  {ticker: 'NEE', Name: 'NextEra Energy', Sector: 'Utilities'},
  {ticker: 'NLSN', Name: 'Nielsen Holdings', Sector: 'Industrials'},
  {ticker: 'NKE', Name: 'Nike', Sector: 'Consumer Discretionary'},
  {ticker: 'NI', Name: 'NiSource Inc.', Sector: 'Utilities'},
  {ticker: 'NBL', Name: 'Noble Energy Inc', Sector: 'Energy'},
  {ticker: 'JWN', Name: 'Nordstrom', Sector: 'Consumer Discretionary'},
  {ticker: 'NSC', Name: 'Norfolk Southern Corp.', Sector: 'Industrials'},
  {ticker: 'NTRS', Name: 'Northern Trust Corp.', Sector: 'Financials'},
  {ticker: 'NOC', Name: 'Northrop Grumman Corp.', Sector: 'Industrials'},
  {ticker: 'NRG', Name: 'NRG Energy', Sector: 'Utilities'},
  {ticker: 'NUE', Name: 'Nucor Corp.', Sector: 'Materials'},
  {ticker: 'NVDA', Name: 'Nvidia Corporation', Sector: 'Information Technology'},
  {ticker: 'ORLY', Name: 'OReilly Automotive', Sector: 'Consumer Discretionary'},
  {ticker: 'OXY', Name: 'Occidental Petroleum', Sector: 'Energy'},
  {ticker: 'OMC', Name: 'Omnicom Group', Sector: 'Consumer Discretionary'},
  {ticker: 'OKE', Name: 'ONEOK', Sector: 'Energy'},
  {ticker: 'ORCL', Name: 'Oracle Corp.', Sector: 'Information Technology'},
  {ticker: 'OI', Name: 'Owens-Illinois Inc', Sector: 'Materials'},
  {ticker: 'PCAR', Name: 'PACCAR Inc.', Sector: 'Industrials'},
  {ticker: 'PH', Name: 'Parker-Hannifin', Sector: 'Industrials'},
  {ticker: 'PDCO', Name: 'Patterson Companies', Sector: 'Health Care'},
  {ticker: 'PAYX', Name: 'Paychex Inc.', Sector: 'Information Technology'},
  {ticker: 'PYPL', Name: 'PayPal', Sector: 'Information Technology'},
  {ticker: 'PNR', Name: 'Pentair Ltd.', Sector: 'Industrials'},
  {ticker: 'PBCT', Name: 'Peoples United Financial', Sector: 'Financials'},
  {ticker: 'PEP', Name: 'PepsiCo Inc.', Sector: 'Consumer Staples'},
  {ticker: 'PKI', Name: 'PerkinElmer', Sector: 'Health Care'},
  {ticker: 'PRGO', Name: 'Perrigo', Sector: 'Health Care'},
  {ticker: 'PFE', Name: 'Pfizer Inc.', Sector: 'Health Care'},
  {ticker: 'PCG', Name: 'PG&E Corp.', Sector: 'Utilities'},
  {ticker: 'PM', Name: 'Philip Morris International', Sector: 'Consumer Staples'},
  {ticker: 'PSX', Name: 'Phillips 66', Sector: 'Energy'},
  {ticker: 'PNW', Name: 'Pinnacle West Capital', Sector: 'Utilities'},
  {ticker: 'PXD', Name: 'Pioneer Natural Resources', Sector: 'Energy'},
  {ticker: 'PBI', Name: 'Pitney-Bowes', Sector: 'Industrials'},
  {ticker: 'PNC', Name: 'PNC Financial Services', Sector: 'Financials'},
  {ticker: 'RL', Name: 'Polo Ralph Lauren Corp.', Sector: 'Consumer Discretionary'},
  {ticker: 'PPG', Name: 'PPG Industries', Sector: 'Materials'},
  {ticker: 'PPL', Name: 'PPL Corp.', Sector: 'Utilities'},
  {ticker: 'PX', Name: 'Praxair Inc.', Sector: 'Materials'},
  {ticker: 'PCLN', Name: 'Priceline.com Inc', Sector: 'Consumer Discretionary'},
  {ticker: 'PFG', Name: 'Principal Financial Group', Sector: 'Financials'},
  {ticker: 'PG', Name: 'Procter & Gamble', Sector: 'Consumer Staples'},
  {ticker: 'PGR', Name: 'Progressive Corp.', Sector: 'Financials'},
  {ticker: 'PLD', Name: 'Prologis', Sector: 'Financials'},
  {ticker: 'PRU', Name: 'Prudential Financial', Sector: 'Financials'},
  {ticker: 'PEG', Name: 'Public Serv. Enterprise Inc.', Sector: 'Utilities'},
  {ticker: 'PSA', Name: 'Public Storage', Sector: 'Financials'},
  {ticker: 'PHM', Name: 'Pulte Homes Inc.', Sector: 'Consumer Discretionary'},
  {ticker: 'PVH', Name: 'PVH Corp.', Sector: 'Consumer Discretionary'},
  {ticker: 'QRVO', Name: 'Qorvo', Sector: 'Information Technology'},
  {ticker: 'QCOM', Name: 'QUALCOMM Inc.', Sector: 'Information Technology'},
  {ticker: 'PWR', Name: 'Quanta Services Inc.', Sector: 'Industrials'},
  {ticker: 'DGX', Name: 'Quest Diagnostics', Sector: 'Health Care'},
  {ticker: 'RRC', Name: 'Range Resources Corp.', Sector: 'Energy'},
  {ticker: 'RTN', Name: 'Raytheon Co.', Sector: 'Industrials'},
  {ticker: 'O', Name: 'Realty Income Corporation', Sector: 'Financials'},
  {ticker: 'RHT', Name: 'Red Hat Inc.', Sector: 'Information Technology'},
  {ticker: 'REGN', Name: 'Regeneron', Sector: 'Health Care'},
  {ticker: 'RF', Name: 'Regions Financial Corp.', Sector: 'Financials'},
  {ticker: 'RSG', Name: 'Republic Services Inc', Sector: 'Industrials'},
  {ticker: 'RAI', Name: 'Reynolds American Inc.', Sector: 'Consumer Staples'},
  {ticker: 'RHI', Name: 'Robert Half International', Sector: 'Industrials'},
  {ticker: 'ROK', Name: 'Rockwell Automation Inc.', Sector: 'Industrials'},
  {ticker: 'COL', Name: 'Rockwell Collins', Sector: 'Industrials'},
  {ticker: 'ROP', Name: 'Roper Industries', Sector: 'Industrials'},
  {ticker: 'ROST', Name: 'Ross Stores', Sector: 'Consumer Discretionary'},
  {ticker: 'RCL', Name: 'Royal Caribbean Cruises Ltd', Sector: 'Consumer Discretionary'},
  {ticker: 'R', Name: 'Ryder System', Sector: 'Industrials'},
  {ticker: 'SPGI', Name: 'S&P Global, Inc.', Sector: 'Financials'},
  {ticker: 'CRM', Name: 'Salesforce.com', Sector: 'Information Technology'},
  {ticker: 'SCG', Name: 'SCANA Corp', Sector: 'Utilities'},
  {ticker: 'SLB', Name: 'Schlumberger Ltd.', Sector: 'Energy'},
  {ticker: 'SNI', Name: 'Scripps Networks Interactive Inc.', Sector: 'Consumer Discretionary'},
  {ticker: 'STX', Name: 'Seagate Technology', Sector: 'Information Technology'},
  {ticker: 'SEE', Name: 'Sealed Air Corp.(New)', Sector: 'Materials'},
  {ticker: 'SRE', Name: 'Sempra Energy', Sector: 'Utilities'},
  {ticker: 'SHW', Name: 'Sherwin-Williams', Sector: 'Materials'},
  {ticker: 'SIG', Name: 'Signet Jewelers', Sector: 'Consumer Discretionary'},
  {ticker: 'SPG', Name: 'Simon Property Group Inc', Sector: 'Financials'},
  {ticker: 'SWKS', Name: 'Skyworks Solutions', Sector: 'Information Technology'},
  {ticker: 'SLG', Name: 'SL Green Realty', Sector: 'Financials'},
  {ticker: 'SJM', Name: 'Smucker (J.M.)', Sector: 'Consumer Staples'},
  {ticker: 'SNA', Name: 'Snap-On Inc.', Sector: 'Consumer Discretionary'},
  {ticker: 'SO', Name: 'Southern Co.', Sector: 'Utilities'},
  {ticker: 'LUV', Name: 'Southwest Airlines', Sector: 'Industrials'},
  {ticker: 'SWN', Name: 'Southwestern Energy', Sector: 'Energy'},
  {ticker: 'SE', Name: 'Spectra Energy Corp.', Sector: 'Energy'},
  {ticker: 'STJ', Name: 'St Jude Medical', Sector: 'Health Care'},
  {ticker: 'SWK', Name: 'Stanley Black & Decker', Sector: 'Consumer Discretionary'},
  {ticker: 'SPLS', Name: 'Staples Inc.', Sector: 'Consumer Discretionary'},
  {ticker: 'SBUX', Name: 'Starbucks Corp.', Sector: 'Consumer Discretionary'},
  {ticker: 'HOT', Name: 'Starwood Hotels & Resorts', Sector: 'Consumer Discretionary'},
  {ticker: 'STT', Name: 'State Street Corp.', Sector: 'Financials'},
  {ticker: 'SRCL', Name: 'Stericycle Inc', Sector: 'Industrials'},
  {ticker: 'SYK', Name: 'Stryker Corp.', Sector: 'Health Care'},
  {ticker: 'STI', Name: 'SunTrust Banks', Sector: 'Financials'},
  {ticker: 'SYMC', Name: 'Symantec Corp.', Sector: 'Information Technology'},
  {ticker: 'SYF', Name: 'Synchrony Financial', Sector: 'Financials'},
  {ticker: 'SYY', Name: 'Sysco Corp.', Sector: 'Consumer Staples'},
  {ticker: 'TROW', Name: 'T. Rowe Price Group', Sector: 'Financials'},
  {ticker: 'TGT', Name: 'Target Corp.', Sector: 'Consumer Discretionary'},
  {ticker: 'TEL', Name: 'TE Connectivity Ltd.', Sector: 'Information Technology'},
  {ticker: 'TGNA', Name: 'Tegna', Sector: 'Consumer Discretionary'},
  {ticker: 'TDC', Name: 'Teradata Corp.', Sector: 'Information Technology'},
  {ticker: 'TSO', Name: 'Tesoro Petroleum Co.', Sector: 'Energy'},
  {ticker: 'TXN', Name: 'Texas Instruments', Sector: 'Information Technology'},
  {ticker: 'TXT', Name: 'Textron Inc.', Sector: 'Industrials'},
  {ticker: 'BK', Name: 'The Bank of New York Mellon Corp.', Sector: 'Financials'},
  {ticker: 'CLX', Name: 'The Clorox Company', Sector: 'Consumer Staples'},
  {ticker: 'KO', Name: 'The Coca Cola Company', Sector: 'Consumer Staples'},
  {ticker: 'HSY', Name: 'The Hershey Company', Sector: 'Consumer Staples'},
  {ticker: 'MOS', Name: 'The Mosaic Company', Sector: 'Materials'},
  {ticker: 'TRV', Name: 'The Travelers Companies Inc.', Sector: 'Financials'},
  {ticker: 'DIS', Name: 'The Walt Disney Company', Sector: 'Consumer Discretionary'},
  {ticker: 'TMO', Name: 'Thermo Fisher Scientific', Sector: 'Health Care'},
  {ticker: 'TIF', Name: 'Tiffany & Co.', Sector: 'Consumer Discretionary'},
  {ticker: 'TWX', Name: 'Time Warner Inc.', Sector: 'Consumer Discretionary'},
  {ticker: 'TJX', Name: 'TJX Companies Inc.', Sector: 'Consumer Discretionary'},
  {ticker: 'TMK', Name: 'Torchmark Corp.', Sector: 'Financials'},
  {ticker: 'TSS', Name: 'Total System Services', Sector: 'Information Technology'},
  {ticker: 'TSCO', Name: 'Tractor Supply Company', Sector: 'Consumer Discretionary'},
  {ticker: 'TDG', Name: 'TransDigm Group', Sector: 'Industrials'},
  {ticker: 'RIG', Name: 'Transocean', Sector: 'Energy'},
  {ticker: 'TRIP', Name: 'TripAdvisor', Sector: 'Consumer Discretionary'},
  {ticker: 'FOXA', Name: 'Twenty-First Century Fox Class A', Sector: 'Consumer Discretionary'},
  {ticker: 'FOX', Name: 'Twenty-First Century Fox Class B', Sector: 'Consumer Discretionary'},
  {ticker: 'TYC', Name: 'Tyco International', Sector: 'Industrials'},
  {ticker: 'TSN', Name: 'Tyson Foods', Sector: 'Consumer Staples'},
  {ticker: 'USB', Name: 'U.S. Bancorp', Sector: 'Financials'},
  {ticker: 'UDR', Name: 'UDR Inc', Sector: 'Financials'},
  {ticker: 'ULTA', Name: 'Ulta Salon Cosmetics & Fragrance Inc', Sector: 'Consumer Discretionary'},
  {ticker: 'UA', Name: 'Under Armour', Sector: 'Consumer Discretionary'},
  {ticker: 'UNP', Name: 'Union Pacific', Sector: 'Industrials'},
  {ticker: 'UAL', Name: 'United Continental Holdings', Sector: 'Industrials'},
  {ticker: 'UNH', Name: 'United Health Group Inc.', Sector: 'Health Care'},
  {ticker: 'UPS', Name: 'United Parcel Service', Sector: 'Industrials'},
  {ticker: 'URI', Name: 'United Rentals, Inc.', Sector: 'Industrials'},
  {ticker: 'UTX', Name: 'United Technologies', Sector: 'Industrials'},
  {ticker: 'UHS', Name: 'Universal Health Services, Inc.', Sector: 'Health Care'},
  {ticker: 'UNM', Name: 'Unum Group', Sector: 'Financials'},
  {ticker: 'URBN', Name: 'Urban Outfitters', Sector: 'Consumer Discretionary'},
  {ticker: 'VFC', Name: 'V.F. Corp.', Sector: 'Consumer Discretionary'},
  {ticker: 'VLO', Name: 'Valero Energy', Sector: 'Energy'},
  {ticker: 'VAR', Name: 'Varian Medical Systems', Sector: 'Health Care'},
  {ticker: 'VTR', Name: 'Ventas Inc', Sector: 'Financials'},
  {ticker: 'VRSN', Name: 'Verisign Inc.', Sector: 'Information Technology'},
  {ticker: 'VRSK', Name: 'Verisk Analytics', Sector: 'Industrials'},
  {ticker: 'VZ', Name: 'Verizon Communications', Sector: 'Telecommunications Services'},
  {ticker: 'VRTX', Name: 'Vertex Pharmaceuticals Inc', Sector: 'Health Care'},
  {ticker: 'VIAB', Name: 'Viacom Inc.', Sector: 'Consumer Discretionary'},
  {ticker: 'V', Name: 'Visa Inc.', Sector: 'Information Technology'},
  {ticker: 'VNO', Name: 'Vornado Realty Trust', Sector: 'Financials'},
  {ticker: 'VMC', Name: 'Vulcan Materials', Sector: 'Materials'},
  {ticker: 'WMT', Name: 'Wal-Mart Stores', Sector: 'Consumer Staples'},
  {ticker: 'WBA', Name: 'Walgreens Boots Alliance', Sector: 'Consumer Staples'},
  {ticker: 'WM', Name: 'Waste Management Inc.', Sector: 'Industrials'},
  {ticker: 'WAT', Name: 'Waters Corporation', Sector: 'Health Care'},
  {ticker: 'WFC', Name: 'Wells Fargo', Sector: 'Financials'},
  {ticker: 'HCN', Name: 'Welltower Inc.', Sector: 'Financials'},
  {ticker: 'WDC', Name: 'Western Digital', Sector: 'Information Technology'},
  {ticker: 'WU', Name: 'Western Union Co', Sector: 'Information Technology'},
  {ticker: 'WRK', Name: 'Westrock Co', Sector: 'Materials'},
  {ticker: 'WY', Name: 'Weyerhaeuser Corp.', Sector: 'Financials'},
  {ticker: 'WHR', Name: 'Whirlpool Corp.', Sector: 'Consumer Discretionary'},
  {ticker: 'WFM', Name: 'Whole Foods Market', Sector: 'Consumer Staples'},
  {ticker: 'WMB', Name: 'Williams Cos.', Sector: 'Energy'},
  {ticker: 'WLTW', Name: 'Willis Towers Watson', Sector: 'Financials'},
  {ticker: 'WEC', Name: 'Wisconsin Energy Corporation', Sector: 'Utilities'},
  {ticker: 'WYN', Name: 'Wyndham Worldwide', Sector: 'Consumer Discretionary'},
  {ticker: 'WYNN', Name: 'Wynn Resorts Ltd', Sector: 'Consumer Discretionary'},
  {ticker: 'XEL', Name: 'Xcel Energy Inc', Sector: 'Utilities'},
  {ticker: 'XRX', Name: 'Xerox Corp.', Sector: 'Information Technology'},
  {ticker: 'XLNX', Name: 'Xilinx Inc', Sector: 'Information Technology'},
  {ticker: 'XL', Name: 'XL Capital', Sector: 'Financials'},
  {ticker: 'XYL', Name: 'Xylem Inc.', Sector: 'Industrials'},
  {ticker: 'YHOO', Name: 'Yahoo Inc.', Sector: 'Information Technology'},
  {ticker: 'YUM', Name: 'Yum! Brands Inc', Sector: 'Consumer Discretionary'},
  {ticker: 'ZBH', Name: 'Zimmer Biomet Holdings', Sector: 'Health Care'},
  {ticker: 'ZION', Name: 'Zions Bancorp', Sector: 'Financials'},
  {ticker: 'ZTS', Name: 'Zoetis', Sector: 'Health Care'}
    

  ];
});
